spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geulgwi
    username: postgres
    password: root

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

jwt:
  secret: abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg