spring:
  datasource:
    url: jdbc:postgresql://geulgwi_postgres:5432/geulgwi
    username: geulgwi_user
    password: geulgwi_pw
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: geulgwi-backend
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.flywaydb: WARN

log:
  path: /logs

openai:
  key: S13P11D202-5351d94c-0223-4f14-9467-2420945e6284
  url: https://gms.ssafy.io/gmsapi/api.openai.com/v1