spring:
  datasource:
    url: jdbc:postgresql://geulgwi_postgres:5432/geulgwi
    username: geulgwi_user
    password: geulgwi_pw
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  file:
    path: /logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
