spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geulgwi
    username: postgres
    password: root

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

jwt:
  secret: abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg

openai:
  key: S13P11D202-5351d94c-0223-4f14-9467-2420945e6284
  url: https://gms.ssafy.io/gmsapi/api.openai.com/v1