spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geulgwi
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

jwt:
  secret: abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg