spring:
  datasource:
    url: jdbc:postgresql://geulgwi_postgres:5432/geulgwi
    username: geulgwi_user
    password: geulgwi_pw
    hikari:
      maximum-pool-size: 80
      minimum-idle: 40
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 3000

  data:
    redis:
      host: redis
      port: 6379
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

aladin:
  ttbkey: ttbhongsbien1441001

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: geulgwi-backend
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.flywaydb: WARN

log:
  path: /logs