contact_links:
  - name: ğŸ™‹ ì§ˆë¬¸/ê¸°íƒ€ ë…¼ì˜
    url: https://github.com/LoveDBug/GEULGWI-BACKEND/discussions
    about: ì´ìŠˆê°€ ì•„ë‹Œ ì¼ë°˜ ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ ë…¼ì˜ëŠ” Discussions íƒ­ì„ ì´ìš©í•´ì£¼ì„¸ìš”